### ISSUE TITLE
Window and Layer range selectors not large enough for negative numbers

### ISSUE THREAD

**Issue by dragondave** [FelixBoiii/paper-plotter#2]
![image](https://user-images.githubusercontent.com/1030130/89717069-bdc9ad00-d9aa-11ea-9730-47302acffa32.png)

On Firefox, the X/Y/Z selectors are too small to show the whole number when the number is negative.

**Comment by FelixBoiii** [comment]
Oh i will need to get rid of the up and down arrows. Thank you!

**Comment by FelixBoiii** [comment]
fixed by adding firefox css
